"""main.py — Entry point for the CoIn Laser Task experiment.

Configuration is loaded from laserTask/config.json (generated by
``python wizard.py``).  If that file doesn't exist, sensible defaults
from laserTask/config.py are used.

Usage:  python main.py
"""
from laserTask.config import get_config
from laserTask.experiment import run_experiment

if __name__ == "__main__":
    cfg = get_config()
    run_experiment(cfg)
